services:
  mongodb:
    image: "mongo:7.0"
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 3s
      timeout: 5s
      retries: 3
      start_period: 2s
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    # command: ["mongod", "--verbose"]
  mongo-express:
    image: mongo-express:latest
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017
      ME_CONFIG_BASICAUTH: "false"
    labels:
      traefik.http.routers.mongo-express.rule: Host(`localhost`)
      traefik.http.services.mongo-express.loadbalancer.server.port: 8081

  backend:
    build:
      context: ./ico-server
      target: backend-dev
    image: ezlixp/wynn-bridge:backend-dev
    env_file: ./ico-server/.env.dockerdev
    restart: on-failure:5
    # port 9229 for debugger to attach
    ports:
      - 9229:9229
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - NODE_ENV=development
    healthcheck:
      test: [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://backend:3000/api/v3/healthz', res =>
          res.statusCode === 200 ? process.exit(0) :
          process.exit(1)).on('error', () => process.exit(1))",
        ]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 2s
    volumes:
      - ./ico-server:/usr/local/backend
      - /usr/local/backend/node_modules
    labels:
      traefik.http.routers.backend.rule: Host(`localhost`) && (PathPrefix(`/api`) || PathPrefix(`/socket.io`))
      traefik.http.services.backend.loadbalancer.server.port: 3000

  bot:
    build:
      context: ./ogybot-discord
      target: bot-dev
    image: ezlixp/wynn-bridge:bot-dev
    restart: unless-stopped
    # for some reason this causes issues sometimes with appsettings not working.
    develop:
      watch:
        - path: ./ogybot-discord
          target: /usr/local/bot
          action: sync
    depends_on:
      backend:
        condition: service_healthy
  proxy:
    image: traefik:latest
    command: --providers.docker
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mongo-data:
